### ISSUE TITLE
Feat: Custom headers

### ISSUE THREAD

**Issue by cj** [jlalmes/trpc-openapi#113]
It would be great to add the ability to define headers https://swagger.io/docs/specification/describing-parameters/#header-parameters.

**Comment by jlalmes** [comment]
This is now supported in `trpc-openapi@0.6.0`, please upgrade and let me know if you have any issues!

**Comment by testerez** [comment]
Thanks for this but how can I then access the header value?

**Comment by jlalmes** [comment]
Pass it through via `ctx` with your `createContext` function.

**Comment by testerez** [comment]
I hopped there where a simpler and more local solution but that works. Thanks @jlalmes
