### ISSUE TITLE
Feat: AWS Lambda handler

### ISSUE THREAD

**Issue by cmaycumber** [jlalmes/trpc-openapi#115]
I'm currently trying to set this up with AWS Lambda do you think the node:http adaptor would be enough to set this up?

**Comment by cmaycumber** [comment]
I don't mind taking a shot at a PR since a lambda adaptor is already in `tRPC` if you're good with that!

**Comment by jlalmes** [comment]
> I don't mind taking a shot at a PR since a lambda adaptor is already in tRPC if you're good with that!

This would be excellent - thank you! 🙏

**Comment by jlalmes** [comment]
Released in `trpc-openapi@v1.0.0-alpha.3` 🎉

**Comment by cmaycumber** [comment]
> Released in `trpc-openapi@v1.0.0-alpha.3` 🎉

Oh man this is awesome thanks!
