### ISSUE TITLE
`input: z.void()` conflicts with trpc client

### ISSUE THREAD

**Issue by dodas** [jlalmes/trpc-openapi#12]
Not sure what's exactly is going on, but when using `trpc-openapi` with a procedure that has `input: z.void()` (or `z.undefined()`, or `z.never()`), I am no longer able to use this procedure via TRPC Client, it fails with following error:
```json
[
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
  }
]
```
Just setting `openapi.enabled` to false (while keeping `input: z.void()`) fixes this and I am able to use the given procedure with no input.
Enabling openapi for given prodedure breaks usage with TRPC Client.

**Comment by jlalmes** [comment]
Also noticed this - resolved in `trpc-openapi@0.1.0-alpha.23`.

**Comment by dodas** [comment]
Thanks, works now.

Curious bug, do you know why that was happening?

**Comment by jlalmes** [comment]
Monkey patched void inputs were mutating the original tRPC router.

Fixed by cloning the router before mutating (line 41)

https://github.com/jlalmes/trpc-openapi/blob/d46ce782b9bb3d0b27db4690ba1d325c36762b9a/src/adapters/node-http/core.ts#L41-L45
