### ISSUE TITLE
RFC: Remove response wrapper

### ISSUE THREAD

**Issue by moogmodular** [jlalmes/trpc-openapi#131]
hi!

i need to satisfy a REST call which i can't influence. is there a way to return the response without the wrapper:

instead of this:

```
{
  "ok": true,
  "data": "This is good" /* Output from tRPC procedure */
}
```

return this:

```
{
  "name": "trpc", /* Output from tRPC procedure */
  "lang": "TS" /* Output from tRPC procedure */
}
```

if not, it would be a nice enhancement since i'm going to be not the only one with this issue. i'm probably going to fork this for now until i'm confident enough to make a PR.

````
const successResponseObject = {
    description: 'Successful response',
    content: {
      'application/json': {
        schema: zodSchemaToOpenApiSchemaObject(
          z.object({
            ok: z.literal(true),
            data: schema,
          }),
        ),
      },
    },
  };
```

**Comment by jlalmes** [comment]
Out of interest, could you explain a little more regarding your use-case and constraints?

I'm keen to hear some more opinions on this. I'm happy to remove our response wrapper as a breaking change in the next major `v1.0.0` if the general consensus is positive.

## Proposed response payload changes

### Success
```diff
- {
-   "ok": true,
-   "data": "This is good"
- }
+ "This is good"
```

### Error
```diff
{
-   "ok": false,
-   "error": {
-     "message": "This is bad",
-     "code": "BAD_REQUEST",
-     "issues": [...]
-   }
+   "message": "This is bad",
+   "code": "BAD_REQUEST",
+   "issues": [...]
}
```

**Comment by moogmodular** [comment]
I'm implementing a REST endpoint in my app for any [ln-url compliant](https://github.com/fiatjaf/lnurl-rfc) bitcoin wallet. In this case i'm generating a [withdrawal request](https://github.com/fiatjaf/lnurl-rfc/blob/luds/08.md) and the wallets expect the response to have certain properties.

```
{
  tag: "string",
  callback: "string",
  k1: "string",
  defaultDescription: "string",
  minWithdrawable: 10,
  maxWithdrawable: 10,
}
```

**Comment by jlalmes** [comment]
Hi @moogmodular, I have implemented this feature and released it under the `alpha` tag. Please upgrade to `trpc-openapi@alpha` and let me know if you have any issues!

**Comment by moogmodular** [comment]
i did and it works exactly as intended.

thank you!

**Comment by jlalmes** [comment]
@moogmodular - I'm just about the publish a new `alpha` version that supports v10. Please make sure you have pinned your `trpc-openapi` version in your `package.json` so that you're unaffected! 

```diff
- "trpc-openapi": "^1.0.0-alpha.0"
+ "trpc-openapi": "1.0.0-alpha.0"
```

(tl;dr - remove the `^`)
