### ISSUE TITLE
Zod `input` and `output` OpenAPI extension support

### ISSUE THREAD

**Issue by huytool157** [jlalmes/trpc-openapi#14]
A very interesting library!

We are using `zod-to-openapi` and there is a extension called `.openapi()` that extends zod and defines the description and example. I wonder how we could do it here so that it's included in the OpenAPI generated spec.

https://github.com/asteasolutions/zod-to-openapi#the-openapi-method

**Comment by jlalmes** [comment]
You can already use `.describe('...')` on your input/output zod schemas and they will be included in your OpenAPI document. 

For example:
```ts
input: z.object({
  id: z.string().uuid().describe("UUID of the user."),
}),
```
Results in this:

<img width="491" alt="Screenshot 2022-06-10 at 17 27 22" src="https://user-images.githubusercontent.com/69924001/173110298-9357b0e7-f52e-4dd7-8756-8c4a3c95e2f6.png">

**Comment by jlalmes** [comment]
Are there any other use-cases covered by the `.openapi(...)` helper that are not supported by `trpc-openapi`?

**Comment by huytool157** [comment]
Oh sweet, I don't know `describe` works. Yeah examples is the one left but I guess putting it in the description is fine. Thanks!
