### ISSUE TITLE
Defaults for meta.openapi.method and meta.openapi.path

### ISSUE THREAD

**Issue by mohsen1** [jlalmes/trpc-openapi#147]
I think to make adoption easier `meta.openapi.method` and `meta.openapi.method` can be optional:

* `meta.openapi.method` is GET for query and POST for mutation. Making deletion with POST is not orthodox but its better to make it optional 
* `meta.openapi.path` can be the mutation/query name. I prefer `/say-hello` to `/sayHello` too, but having the former as an option also makes adoption easier. 

Thoughts?

**Comment by jlalmes** [comment]
It has been agreed at this time that `meta.openapi.method` and `meta.openapi.path` will be the minimum requirements to enable OpenAPI support for a tRPC procedure. See https://github.com/jlalmes/trpc-openapi/issues/68.
