### ISSUE TITLE
[Help wanted] T3 Stack and Queryparameters

### ISSUE THREAD

**Issue by JeromeK13** [jlalmes/trpc-openapi#149]
Hey Guys

I've started using the T3 Stack with trpc / nextjs and wanted to use this awesome package to my Project.
Everything works fine and I see the OpenAPI-Docs in the expected route. But i dont understand why this happens

When looking at my trpc query, I have the following:
```ts
export const exampleRouter = createRouter().query("hello", {
  meta: { openapi: { enabled: true, method: "GET", path: "/api/trpc/example.hello" } },
  input: z.object({ name: z.string() }),
  output: z.object({ greeting: z.string() }),
  resolve: ({ input }) => {
    return { greeting: `Hello ${input.name}!` };
  },
});
```
which generated the OpenAPI docs but when i try to execute it throught the UI it generates the URL like this:
`http://0.0.0.0:3000/api/trpc/example.hello?name=asdf` which is of course not wrong. But when looking into the dev-tools on my page the request generated from trpc-client is generated like this:
`http://localhost:3000/api/trpc/example.hello?batch=1&input={"0":{"json":{"name":"jerome"}}}`

Can i change this behavior for the generation of the OpenAPI docs or how would you recommend trying to fix this?

Thanks in advanced
Jerome

**Comment by jlalmes** [comment]
Hi @JeromeK13, I think you've misunderstood the purpose of this package. 

* `trpc-openapi` is a server-side only package. 
* `trpc-openapi` exposes OpenAPI compliant versions of your tRPC procedures. 
* `trpc-openapi` does not affect your `@trpc/client`. 

If you wish to call the OpenAPI endpoint from your client you will need to do the following:
```ts
const res = await fetch('/api/example.hello?name=asdf');
const body = await res.json();
```

See our NextJS example project here: 
https://github.com/jlalmes/trpc-openapi/tree/master/examples/with-nextjs

Let me know if you have any more questions/issues!

**Comment by JeromeK13** [comment]
Hey
Thanks for the answer but not quite what i was searching for

When calling the trpc-function i do the following
```ts
const { data, isLoading } = trpc.useQuery([
    "example.hello",
    { name: "jerome" },
  ]);
```
This works as expected and when inspecting the chrome-dev-network traffic the request is handled like this
`http://localhost:3000/api/trpc/example.hello?batch=1&input={"0":{"json":{"name":"jerome"}}}`

But in the OpenAPI-Docs the Request gets generated like this
`http://localhost:3000/api/trpc/example.hello?name=jerome` which fails since `batch`  and `input` params are missing.

Any ideas where to find the issue? Hope is clearer now 😅

**Comment by jlalmes** [comment]
Have you added `createOpenApiNextHandler`?  

https://github.com/jlalmes/trpc-openapi/blob/master/examples/with-nextjs/src/pages/api/%5B...trpc%5D.ts

**Comment by JeromeK13** [comment]
Yes just saw that one, implemented it and works fine no - except the /api/example.hello does not get found

when trying to call /api/example.hello?name=XY

**Comment by JeromeK13** [comment]
Ive tried that but it would be 
`meta: { openapi: { enabled: true, method: "GET", path: "/api/example.hello" } },` based on the project structure no?
Because when im trying this without /api - Nextjs is trying to render this site

**Comment by jlalmes** [comment]
No because your `createOpenApiNextHandler` is located at `pages/api/[...trpc].ts`, hence `/api` is your baseUrl.

* `path: "/example.hello"` -> `/api/example.hello`
* `path: "/api/example.hello"` -> `/api/api/example.hello`

Have you got it working now?

**Comment by JeromeK13** [comment]
Ahhh got it many thanks works now, awesome :) and again many thanks for your patient

**Comment by isaacguerreir** [comment]
> @JeromeK13, please look at our NextJS example project here: https://github.com/jlalmes/trpc-openapi/tree/master/examples/with-nextjs
> 
> * You need to have a `createOpenApiNextHandler` to resolve OpenAPI requests.
> * You **also** need to have a `createNextApiHandler` to resolve tRPC requests.
> 
> ```
> - pages
>   - api
>     - [...trpc].ts 👈 OpenAPI requests are handled here at `localhost:3000/api/...`
>     - /trpc
>       - [...trpc].ts 👈 tRPC requests are handled here at `localhost:3000/api/trpc/...`
> ```
> 
> Does this make sense?

It's interesting because I don't think it's very clear in the `README.md`  of the repository on the example `with Next.js` that you should have two API Handlers, one for TRPC and the other one for the OpenAPI.

I think my natural mental model when reading the documentation is:  `createOpenApiNextHandler` should be the TRPC API handler appended with OpenAPI endpoints. You don't need two API handlers, only one using the `createOpenApiNextHandler` function to have both.

**Comment by jlalmes** [comment]
tRPC and OpenAPI endpoints could conflict, hence they need to be handled separately.

Example:
```
These two conflict
GET /updates 👈 tRPC endpoint
GET /updates 👈 OpenAPI endpoint

Resolved by
GET /trpc/updates 👈 tRPC endpoint
GET /updates 👈 OpenAPI endpoint
```

**Comment by jlalmes** [comment]
Thanks for the feedback though @isaacguerreir! Would you be willing to open a PR that explains this more concisely in the `README`?

**Comment by imding** [comment]
> @JeromeK13, please look at our NextJS example project here: https://github.com/jlalmes/trpc-openapi/tree/master/examples/with-nextjs
> 
> * You need to have a `createOpenApiNextHandler` to resolve OpenAPI requests.
> * You **also** need to have a `createNextApiHandler` to resolve tRPC requests.
> 
> ```
> - pages
>   - api
>     - [...trpc].ts 👈 OpenAPI requests are handled here at `localhost:3000/api/...`
>     - /trpc
>       - [...trpc].ts 👈 tRPC requests are handled here at `localhost:3000/api/trpc/...`
> ```
> 
> Does this make sense?

this helped, thanks a lot!
