### ISSUE TITLE
Refactoring express example to thr own router file causes weird error 

### ISSUE THREAD

**Issue by jascodes** [jlalmes/trpc-openapi#155]
@jlalmes 

Awesome work on this package. I am getting this weird issue, take a look.

I am trying to take out for example here postsProtectedRouter to its own file. But typescript is yelling at me.

```
export const postsProtectedRouter = createProtectedRouter()
                                                         ^
TypeError: (0 , index_1.createProtectedRouter) is not a function
```

**Comment by jlalmes** [comment]
Hi @jascodes, I can't really help without a reproduction.

**Comment by jascodes** [comment]
@jlalmes Mate, I solved it I was weird as this was only happening from index.ts file, changing that fixed it. Still don't understood what was trigging this.

Thx
