### ISSUE TITLE
TRPCError: Input parser must be a ZodObject

### ISSUE THREAD

**Issue by SteveMelons** [jlalmes/trpc-openapi#161]
I am getting the following error: `TRPCError: Input parser must be a ZodObject`

I have looked through all the previous issues and can't seem to figure out what I am doing wrong. I have one route
```ts
const createRouter = () => trpc.router<Context, OpenApiMeta>();

export const appRouter= createRouter().query("hello", {
  meta: { openapi: { enabled: true, method: "GET", path: "/hello" } },
  input: z
    .object({
      text: z.string().nullish(),
    })
    .nullish(),
  output: z.object({ greeting: z.string() }),
  resolve({ input }) {
    return {
      greeting: `Hello ${input?.text ?? "world"}`,
    };
  },
});
```
and as you can see I do have zod as the input parser.

**Comment by jlalmes** [comment]
Hi @SteveMelons, what version of `trpc-openapi` are you using?

**Comment by jlalmes** [comment]
Hi @SteveMelons, can you check which version you using?

* `trpc-openapi@^0` only supports `@trpc/server@^9`
* `trpc-openapi@^1` only supports `@trpc/server@^10`

I suspect you are using `v0.7.0` when you should be using `v1.0.0-alpha.1`

To get started, please see 👉 https://github.com/jlalmes/trpc-openapi/blob/next/README.md
Full list of breaking changes 👉 https://github.com/jlalmes/trpc-openapi/pull/143

**Comment by martin-fv** [comment]
I'm trying out v1.0.0-alpha.1, 
@jlalmes why does an input need to be enabled for the openAPI extension?
@SteveMelons try to remove .nullish() and it should work.

**Comment by mshd** [comment]
I'm trying out v1.0.0-alpha.1,
@jlalmes why does an input need to be enabled for the openAPI extension?
@SteveMelons try to remove .nullish() and it should work.

**Comment by mshd** [comment]
@jlalmes why does an input need to be enabled for the openAPI extension?
@SteveMelons try to remove .nullish() and see if it works.
