### ISSUE TITLE
Getting Error :  Input parser key: "from" must be ZodString

### ISSUE THREAD

**Issue by Manuelbaun** [jlalmes/trpc-openapi#166]
Hey thanks for this library, 

I am trying to understand why the value of an input objects must be a ZodString. I get following error : ` Input parser key: "from" must be ZodString`

```
  input: z.object({
        from: z.number(),
        to: z.number(),
    }),
```

I read here https://github.com/jlalmes/trpc-openapi/blob/next/README.md that the input object is defined as  `ZodObject<{ [string]: ZodString }>` but [openApiSpec](https://swagger.io/docs/specification/data-models/data-types/) also allows number/ integer etc 

at least number would be good.

**Comment by jlalmes** [comment]
It's because query string parameters are `string`s.

Try this:
```ts
input: z.object({
  from: z.preprocess((arg) => parseInt(arg), z.number()),
  to: z.preprocess((arg) => parseInt(arg), z.number()),
}),
```

**Comment by jlalmes** [comment]
@elmeister I think you've gotten confused between [`tRPC`](https://github.com/trpc/trpc) and this `trpc-openapi` adapter repo.

**Comment by elmeister** [comment]
It's this adapter that needs excessive `preprocess`, tRPC is fine.

**Comment by jlalmes** [comment]
😂 thanks for your input. 

This is actually resolved by `coerce` introduced in the next `zod` version (https://github.com/colinhacks/zod/releases/tag/v3.20.0). 

I recommend reading our `README` to understand the `trpc-openapi` use-case and how to use it.

**Comment by elmeister** [comment]
These days there are plenty of readme and quite a few good modules, which just do what they supposed to do, isn't it?

**Comment by msalahz** [comment]
Can you please add coerce support?
