### ISSUE TITLE
Understanding compression compared to normal openapi 

### ISSUE THREAD

**Issue by kyeshmz** [jlalmes/trpc-openapi#173]
Hi thanks for the awesome package!

I am still a beginner using tRPC and am using this package to incrementally add a trpc layer into my projects.
I was wondering if there is a possibility of using compression algos such as gzip to the body response.
I understand that [data transformers](https://trpc.io/docs/data-transformers) are not supported, but is this out of scope due to how trpc would compress as discussed [here](https://github.com/trpc/trpc/issues/1925)? 

It seems like something that isn't really applicable to normal tRPC

**Comment by jlalmes** [comment]
Compression like `gzip` is probably out of scope for tRPC and is already handled by frameworks (such as NextJS) & some hosting service provider out of the box.
