### ISSUE TITLE
How to protect endpoints with oauth 2.0

### ISSUE THREAD

**Issue by virus2016** [jlalmes/trpc-openapi#174]
Just wondering if there is a quick example on how to add the oauth 2.0 authorization protocol for endpoint protection?

**Comment by jlalmes** [comment]
While `OAuth` implementation is completely possible with `trpc-openapi`, providing an example is out of scope. Please take a look at other purpose built libraries such as [`next-auth`](https://next-auth.js.org/configuration/providers/oauth).
