### ISSUE TITLE
Where to find OpenAPI specification

### ISSUE THREAD

**Issue by niklashempel** [jlalmes/trpc-openapi#176]
Is there a URL where one can get the JSON/YAML?

**Comment by jlalmes** [comment]
You must use `generateOpenApiDocument` to create an OpenAPI JSON spec. You can then serve this on an API route if you wish. 

Please see example 👉 https://github.com/jlalmes/trpc-openapi/blob/next/examples/with-nextjs/src/pages/api/openapi.json.ts
