### ISSUE TITLE
Path params

### ISSUE THREAD

**Issue by dodas** [jlalmes/trpc-openapi#2]
Hey @jlalmes, this is a great little library!

I am exploring possibilities and as far as I can understand, there is currently no way to define a [`path` parameter](https://swagger.io/docs/specification/describing-parameters/#path-parameters).
Consider the [petstore swagger example](https://petstore.swagger.io/#/pet/uploadFile), the `uploadFile` has `petId` parameter, which is part of the path.

Could we try to extract the path params by looking for curly braces in `meta.openapi.path`, and then find param with the same name in `input` and mark that param as `from: "path"` instead of `from: "query"`?

WIP attempt to implement the above approach: https://github.com/jlalmes/trpc-openapi/compare/v0.1.0...dodas:feat/path-parameters

Have you thought about supporting this use case?
I am happy to discuss this and potentially take a stab at implementing it.

Thanks!

**Comment by jlalmes** [comment]
Initially it was considered adding `path` parameter support when creating the library but I decided to leave it unsupported due to tRPC having no similar concept and the DX getting somewhat complicated.

I'm open for adding support if there is a requirement though, could you explain your needs for `GET /user/some-user-id` instead of `GET /user?id=some-user-id`?

**Comment by dodas** [comment]
I think using path parameters for identifying an item within collection is a common (best) practice.
See from the [docs](https://swagger.io/docs/specification/describing-parameters/#path-parameters):
> They (path parameters) are typically used to point to a specific resource within a collection, such as a user identified by ID

We currently already have a couple of rest endpoints with path parameters and we are not trying them to migrate to `trpc-openapi` without making breaking changes to our public API.

What do you think about my proposed solution? It seems the model remains quite straightforward, where `input` object still remains the truth of source for all your parameters, but then those ones that are "mentioned" in path would be considered path parameters instead of query params.

**Comment by jlalmes** [comment]
> We currently already have a couple of rest endpoints with path parameters and we are not trying them to migrate to trpc-openapi without making breaking changes to our public API.

Ok, let's support this!

## Breaking change

Input for queries is restricted to `ZodObject({ [string]: ZodString })` schema, however input for mutations is currently unrestricted and can be any `ZodType`. The proposed solution introduces a breaking change requiring mutation inputs to follow `ZodObject({ [string]: ZodType })` schema. 

I don't think isn't a _huge_ issue (currently in alpha) but just want to raise.

## Usage

```ts
trpc.router()
  .query('getUserById', {
    meta: { openapi: { enabled: true, method: 'GET', path: '/user/{userId}' } },
    input: z.object({ // validated as ZodObject({ [string]: ZodString })
      userId: z.string(), // `userId` is required in schema because it is used in path
      teamId: z.string(),
    }),
    output: ...,
    resolve: ...,
  })
  .mutation('updateUserById', {
    meta: { openapi: { enabled: true, method: 'PUT', path: '/user/{userId}' } },
    input: z.object({ // validated as ZodObject({ [string]: ZodType })
      userId: z.string(), // `userId` is required in schema & validated as ZodString
      details: z.object({
        name: z.string(),
      }),
    }),
    output: ...,
    resolve: ...,
  })
```

Obviously paths with multiple parameters should be supported too e.g.`/team/{teamId}/user/{userId}`

```
GET /user?userId=user_123
> 404 NOT_FOUND

GET /user/user_123
> 400 BAD_REQUEST

GET /user/user_123?teamId=team_123
> { userId: 'user_123', teamId: 'team_123' }

GET /user/user_123?teamId=team_123&userId=user_456 // do not overwrite
> { userId: 'user_123', teamId: 'team_123' }
```

```
POST /user {"userId":"user_123"}
> 404 NOT_FOUND

POST /user/user_123
> 400 BAD_REQUEST

POST /user/user_123 {"teamId":"team_123"}
> { userId: 'user_123', teamId: 'team_123' }

POST /user/user_123 {"teamId":"team_123","userId":"user_345"} // do not overwrite
> { userId: 'user_123', teamId: 'team_123' }
```

A quick scan of your PR looks great, I will review properly and add some tests tomorrow.

Thanks @dodas!

**Comment by jlalmes** [comment]
Hi @dodas, support for `path` parameters has just shipped, thanks for your help! 🚀

Please can you upgrade to `trpc-openapi@0.1.0-alpha.20` & let me know if you find any issues. Keen to release `v0.1.0` soon - so feedback is appreciated.

**Comment by dodas** [comment]
Perfect, thanks!!
From testing so far, everything seem to work as expected 💯
