### ISSUE TITLE
Option to ignore output validation?

### ISSUE THREAD

**Issue by baptisteArno** [jlalmes/trpc-openapi#202]
Output validation is required by `trpc-openapi` to generate the valid response schema, but then maybe we don't really want to enable runtime output validation for our procedures.

I'm not sure what would be the ideal solution here.

Is there any way to ignore the runtime output validation?

**Comment by jlalmes** [comment]
Not currently, here's two possibilities if you desperately need this:

1. Open PR to disable runtime output validation with some config (ie. `disableOutputValidation`) in [`trpc`](https://github.com/trpc/trpc).
2. Remove `trpc-openapi` output schema requirement, and generate output OpenAPI schema from static type analysis with `trpc-snapshot` (currently private) (cc. https://github.com/jlalmes/trpc-openapi/issues/61#issuecomment-1180611408)
