### ISSUE TITLE
Missing explanation for running the express example project

### ISSUE THREAD

**Issue by default-kaas** [jlalmes/trpc-openapi#212]
# Missing explanation for running the express example project
## Missing build script
When trying to use the trpc-openapi with express example project you will get an error saying that the script for building the project is missing.

![image](https://user-images.githubusercontent.com/23498867/209575718-6a4c3dcb-65d7-4733-8e82-9710c038f53d.png)

And when looking into the package.json it seems to be missing:
https://github.com/jlalmes/trpc-openapi/blob/6ffa9f540ac0c6e80ed1ffdcca0fd0062191eb41/examples/with-express/package.json#L5-L7

## Missing trpc-openapi
When running NPM run dev and  npm run dev -w with-express you will get the following error:
![image](https://user-images.githubusercontent.com/23498867/209575297-7618fe18-8806-4850-b0e3-59f62ffab48f.png)

## Missing main entry
After installing the TRPC-openapi it will throw the following error:
![image](https://user-images.githubusercontent.com/23498867/209575486-dd8606ac-7f63-40f2-a301-740bafa4a4c5.png)

# Solution:
Can someone who knows how to run this project update the READ.ME of the with express example?
I suspect that I am missing a step that is necessary for running the example project.

https://github.com/jlalmes/trpc-openapi/blob/master/examples/with-express/README.md

**Comment by jlalmes** [comment]
The [`README`](https://github.com/jlalmes/trpc-openapi/tree/master/examples/with-express#readme) outlines exactly how to get the example running.

> Make sure your current working directory is at /trpc-openapi root.

```
npm install
npm run build
npm run dev -w with-express
```
