### ISSUE TITLE
Feature: Infer type from output

### ISSUE THREAD

**Issue by ollydixon** [jlalmes/trpc-openapi#216]
In my of our endpoints we don't include the Output definition because it's automatically inferred by tRPC.

We feel like it's a step backwards having to define the output each time.

```
export const health = publicProcedure
  .meta({ openapi: { method: 'POST', path: '/health', tags: ['admin'], protect: false } })
  .input(
    z.void(),
    //
  )
  .output(z.any()) << This is not needed. tRPC knows the type without it.
  .mutation(async ({ ctx, input }) => {
    return { status: nanoid(9) };
  });

```

**Comment by jlalmes** [comment]
Duplicate - please search issues

**Comment by ollydixon** [comment]
@jlalmes ah ok, so no obvious solution. Will stick to any. Thanks for the great library btw.
