### ISSUE TITLE
Support multipart/form-data

### ISSUE THREAD

**Issue by harveylee** [jlalmes/trpc-openapi#229]
In v1.0.0, we were using middleware to call `busboy` to parse requests with `content-type: multipart/form-data` for uploads.

In v1.1.0 the more stringent test on the `content-type` header now prevents that.

Perhaps this library could support `multipart/form-data` directly? Or allow us to override the `content-type` check so that our middleware can  process the form data?

For reference, our endpoint looks something like:

```ts
import { Busboy } from '@fastify/busboy'
// ...other imports

const parseUpload = middleware(async ({ ctx, next, rawInput }) => {
  await new Promise<void>((resolve, reject) => {
    const busboy = new Busboy({ headers: ctx.req.headers })
    let uploadedFile: UploadedFileType

    busboy.on('file', () => { /* handle file */ })
    busboy.on('field', (fieldName, value) => {
      Object.assign(rawInput as object, { [fieldName]: value })
    })
    busboy.on('finish', () => {
      Object.assign(rawInput as object, { file: uploadedFile })
      resolve()
    })

    if (ctx.req.rawBody !== undefined) {
      busboy.end(ctx.req.rawBody)
    } else {
      ctx.req.pipe(busboy)
    }
  })

  return await next()
})

const myRouter = router({
  upload: procedure.use(parseUpload).meta({ /* openapi: { ... } */}) // etc.
})
```

**Comment by jlalmes** [comment]
I don't think we should implement `multipart/form-data` support at this time, but I have fixed the tight Content-Type checks so your current implementation should work.

Please upgrade to `v1.1.1` and let me know if you have any issues!

**Comment by harveylee** [comment]
Brilliant, that works. Thank you.

FYI I am later using `generateOpenApiDocument` on the router, and then I replace `post.requestBody.content['application/json']` with `post.requestBody.content['multipart/form-data']` for that endpoint. So perhaps you could also consider allowing the user to specify any (? valid?) `contentType` in the meta to be passed through to the Open API document?

**Comment by jlalmes** [comment]
@harveylee, will do!

It should work already, I just need to update the typings try this

```ts
contentTypes: ['multipart/form-data'] as any,
```
