### ISSUE TITLE
Prisma optional fields not acccepted by zod object in output 

### ISSUE THREAD

**Issue by hsit18** [jlalmes/trpc-openapi#246]
I have a use case where I am using optional fields for Prisma modal as below
```
model User {
  id      String   @id @default(auto()) @map("_id") @db.ObjectId
  email   String   @unique
  name    String?
}
```

Now, I have implemented User create API to define zod object type for output structure.
 
```
    createUser: t.procedure
        .meta({
            openapi: {
                method: 'POST',
                path: '/users/createUser',
                tags: ['users'],
                summary: 'Create new user',
            },
        })
        .input(z.object({ name: z.string().min(5), email: z.string().email() }))
        .output(z.object({ id: z.string().uuid(), name: z.string().nullable(), email: z.string().email() }))
        .mutation(async (req) => {
            const user: User = await prisma.user.create({
                data: req.input,
            });
            return user;
        }),
```
TRPCError: Output validation failed\n    at outputMiddleware (/Users/harpreetsingh/Documents/Projects/trpc-app/node_modules/@trpc/server/dist/index.js:288:19)

**Comment by jlalmes** [comment]
Need some more information here, what is the full `TRPCError: Output validation failed` error?

Even better, could you provide a StackBlitz reproduction?

**Comment by hsit18** [comment]
@jlalmes Thanks for your quick reply.

I have pushed my code to [GitHub](https://github.com/hsit18/trpc-app)
Currently, in output I have used z.any(), but I need to use the type of User (Prisma model) which has property as
{
  id      String   
  email   String
  **name    String?
  password String?**
  posts   Post []
}

Since name & password are optional, so I have created the below zod object in the output
z.object({ id: z.string().uuid(), name: z.string().nullable(), password: z.string().nullable(), email: z.string().email() })
API error screenshot attached 
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/6747765/214921326-12a672a2-5752-4f61-9a40-9a3626394b3b.png">

**Comment by jlalmes** [comment]
Your repo is private. Can you share access with me.

**Comment by hsit18** [comment]
now the repo is public.
https://github.com/hsit18/trpc-app

**Comment by jlalmes** [comment]
I cannot find the `/api/create` endpoint you're showing in that repo, nor can I find any OpenAPI enabled procedures at all.

You should be able to see the output validation `zod` error in the console and that should give you more information about what is going wrong. My initial assumption is that your `id` is an MongoDB ObjectId instead of a `uuid` and is therefore failing.

Closing for now, but if you can provide a StackBlitz/CodeSandbox reproduction I'm happy to take a look.

**Comment by hsit18** [comment]
@jlalmes stackblitz/codesandbox is not possible due prisma binaries issues.
Request you to clone github project and follow the below steps:

1. npm install
2. add .env with DATABASE_URL= <MONGO_DB_CONNECTION_URL>
3. npm run database-generate
4. npm run dev . Will launch app on http://localhost:3000
5. Execute below API
     URL: http://localhost:3000/api/create
     Method: POST
     body: {"name": "test", "email": "test@test.com"}

**Comment by hsit18** [comment]
@jlalmes thanks for your help.
I got the issue, MongoDB id (ObjectId) was mapped to string, for it works with z.any().
Please suggest a proper validator for MongoDB ObjectID.

Also, Can we use the existing Prisma Model Type from @prisma/client (User in my case) with Zod validator? If yes then please share some sample code snippets

**Comment by jlalmes** [comment]
> Please suggest a proper validator for MongoDB ObjectID.

🤷‍♂️ you'll have to figure that out for yourself.

> use the existing Prisma Model Type from @prisma/client (User in my case) with Zod validator?

This tool might be useful to you 👉 [zod-prisma](https://github.com/CarterGrimmeisen/zod-prisma).

**Comment by hsit18** [comment]
> > Please suggest a proper validator for MongoDB ObjectID.
> 
> 🤷‍♂️ you'll have to figure that out for yourself.
> 
> > use the existing Prisma Model Type from @prisma/client (User in my case) with Zod validator?
> 
> This tool might be useful to you 👉 [zod-prisma](https://github.com/CarterGrimmeisen/zod-prisma).

thanks @jlalmes
