### ISSUE TITLE
Zod .nullish() not supported

### ISSUE THREAD

**Issue by sethgw** [jlalmes/trpc-openapi#250]
When attempting to use `.nullish()` I receive an error:

`Input parser key: "searchTerm" must be ZodString, ZodNumber, ZodBoolean, ZodBigInt or ZodDate`

zod Key -> searchTerm: z.string().nullish()

the type ends up being: `z.ZodNullable<z.ZodOptional<z.ZodNumber>>`

**Comment by jlalmes** [comment]
Inputs cannot be `null`. Use `z.string().optional()`.

**Comment by anis-dr** [comment]
@jlalmes why though? it should accept null since JSON have support for it
