### ISSUE TITLE
responseMeta example

### ISSUE THREAD

**Issue by timmattison** [jlalmes/trpc-openapi#251]
The documentation says that you can change the HTTP status code on responses by using responseMeta. I looked around and didn't see an example. Is there documentation for this? Autocomplete is failing me on this so I'm not seeing where responseMeta would be accessed.

What I'm looking to do is to change my status code to 201 to indicate a record was created to be compatible with existing systems that depend on it.

**Comment by StyxOfDynamite** [comment]
I was wondering the same, I found I can specify a `responseMeta` function, like so.

```
responseMeta: () => ({ status: 202 }),
```

But seemingly only when I create the `api` route, at which point I don't know what the response code would be.
```
// Handle incoming OpenAPI requests
app.use(
  "/api",
  createOpenApiExpressMiddleware({
    router: appRouter,
    createContext,
    responseMeta: () => ({ status: 202 }),
  })
);
```
