### ISSUE TITLE
Next.js adapter doesn't generate error status codes in openapi.json

### ISSUE THREAD

**Issue by mael-queau** [jlalmes/trpc-openapi#258]
I have set up two routes in order to see how trpc-openapi generated error responses in the spec file, but I can't seem to get it to work.

Here is the resulting spec:
```yaml
/error/bad-request:
    get:
      operationId: query.error.badRequest
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
        default:
          $ref: '#/components/responses/error'
  /error/too-many-requests:
    get:
      operationId: query.error.tooManyRequests
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: {}
        default:
          $ref: '#/components/responses/error'
```

And here is the TypeScript definition:

```ts
import { z } from "zod";

import { createTRPCRouter, publicProcedure } from "../trpc";
import { TRPCError } from "@trpc/server";

export const errorRouter = createTRPCRouter({
  badRequest: publicProcedure
    .meta({
      openapi: {
        method: "GET",
        path: "/error/bad-request",
      },
    })
    .input(z.void())
    .output(z.void())
    .query(() => {
      throw new TRPCError({
        code: "BAD_REQUEST",
        message: "Bad request",
      });
    }),
  tooManyRequests: publicProcedure
    .meta({
      openapi: {
        method: "GET",
        path: "/error/too-many-requests",
      },
    })
    .input(z.void())
    .output(z.void())
    .query(() => {
      throw new TRPCError({
        code: "TOO_MANY_REQUESTS",
        message: "Too many requests",
      });
    }),
});
```

Using cURL on the REST endpoints, I can see that the proper response codes are returned, but I don't understand why that doesn't show up in the spec. Is that intended behaviour, or do I need to do something different?

**Comment by jlalmes** [comment]
[Currently](https://github.com/jlalmes/trpc-openapi/issues/61#issuecomment-1180611408), we cannot infer tRPC procedure return types as values, so it is not possible to generate an OpenAPI schema with the correct status code. The error schema is under the fallback `default` status code.

**Comment by mael-queau** [comment]
> [Currently](https://github.com/jlalmes/trpc-openapi/issues/61#issuecomment-1180611408), we cannot infer tRPC procedure return types as values, so it is not possible to generate an OpenAPI schema with the correct status code. The error schema is under the fallback `default` status code.

Thank you very much, I was wondering about that :)

Either way, thank you very much for this library, it's a real life-saver!
