### ISSUE TITLE
createTRPCProxyClient from @trpc/client does not respect the openapi path field

### ISSUE THREAD

**Issue by excursus** [jlalmes/trpc-openapi#259]
To take the example from the README, if I create a router with the endpoint:
```typescript
...
    sayHello: t.procedure
        .meta({ openapi: { method: 'GET', path: '/say-hello/{name}' /* 👈 */ } })
        .input(z.object({ name: z.string() /* 👈 */, greeting: z.string() }))
        .output(z.object({ greeting: z.string() }))
        .query(({ input }) => {
            return { greeting: `${input.greeting} ${input.name}!` }
        }),
```

And then later I create a client from this router like this:
```typescript
const client = createTRPCProxyClient<AppRouter>({
    links: [httpBatchLink({ url: "..." }),
    ],
})
```
And then finally invoke the client on this endpoint like this:
```typescript
await client.sayHello.query({ greeting: 'hello', name: 'foobar' })
```
the client his an url at `/sayHello?batch=1&input=%7B%220%22%3A%7B%22greeting%22%3A%22hello%22%2C%22name%22%3A%22foobar%22%7D%7D` rather than `/say-hello?/foobar`.

**Comment by jlalmes** [comment]
This is correct. The `trpc-openapi` handler exposes your `@trpc/server` procedures as REST-compliant endpoints. It does not affect the behavior of `@trpc/client`
