### ISSUE TITLE
Prefixing routes

### ISSUE THREAD

**Issue by collinc777** [jlalmes/trpc-openapi#260]
I'd like to prefix all routes for a router. As an example I'd like to be able to have a few different routes for a star wars api.

I'd like them to look like: /starwars/characters, /starwars/places, ...etc

Is there anyway to do that?

**Comment by Nick-Lucas** [comment]
Just wrap your router in another router:

```ts
const starwarsRouter = createRouter({
  places: createRouter({
    // your procedures
  })
})

const appRouter = createRouter({
  starwars: starwarsRouter
})
```

**Comment by jlalmes** [comment]
Because it is not possible to attach `.meta` to a tRPC router, this is not currently supported. 

You need to enter the full `"/starwars/xxx"` path for each procedure.
