### ISSUE TITLE
RFC: Add `"examples"` to OpenAPI schema

### ISSUE THREAD

**Issue by rhinodavid** [jlalmes/trpc-openapi#261]
I'm looking for a way to add openapi annotations to inputs and outputs.. something like:
```
// Router
export const appRouter = t.router({
  sayHello: t.procedure
    .meta({ openapi: { method: 'GET', path: '/say-hello/{name}' } })
    .input(z.object({ name: z.string().openapi({ description: "Your full name", example: "Sonny Moore" }) /* 👈 */, greeting: z.string() }))
    .output(z.object({ greeting: z.string() }))
    .query(({ input }) => {
      return { greeting: `${input.greeting} ${input.name}!` };
    });
});
```

The [`zod-to-openapi`](https://github.com/asteasolutions/zod-to-openapi) extension enables the openapi annotation, but you have to then manually create each path.

What would great is a mashup of `trpc-openapi` and `zod-to-openapi`.

I think this would be possible by swapping out the [`zod-to-json-schema`](https://github.com/StefanTerdell/zod-to-json-schema) library with the generator in `zod-to-openapi`.

If there's interest in this I might be able to spend some time on it.

**Comment by jlalmes** [comment]
It is already possible to provide a description to a field using `.describe(string)` eg. 

```diff
- .input(z.object({ name: z.string().openapi({ description: "Your full name", example: "Sonny Moore" }) /* 👈 */, greeting: z.string() }))
+ .input(z.object({ name: z.string().describe('Your full name') /* 👈 */, greeting: z.string() }))
```

As you are not the first one to ask for this feature, I think we should add an `examples` property to `OpenApiMeta` object so that we can [generate "examples" schemas](https://swagger.io/docs/specification/adding-examples/) in the OpenAPI document. 

```ts
.meta({ 
  openapi: { 
    method: 'GET', 
    path: '/say-hello/{name}',
    // 👇 Any thoughts on this API? 
    examples: {
      input: [{ name: 'Sonny Moore', greeting: 'Hello' }],
      output: [{ greeting: 'Hello Sonny Moore!' }]
    }
  } 
})
```

PS. one of my fave songs of all time 👉 https://www.youtube.com/watch?v=AM3J4428cyc

**Comment by tcaputi** [comment]
I literally was about to file this as an issue. And the propsed api was pretty close to what i was going to suggest.

**Comment by rhinodavid** [comment]
Somebody finally got one of my skrill references!

Instead of doing just the example what if we allowed the [`BaseParameterObject`](https://github.com/metadevpro/openapi3-ts/blob/master/src/model/OpenApi.ts#L153) to be specified?

Maybe
```
.meta({ 
  openapi: { 
    method: 'GET', 
    path: '/say-hello/{name}',
    inputMeta: 
      [{ name: { examples: ["eric", "stan" }, greeting: { deprecated: true }],
    outputMeta: [{ greeting: { example: "hidey ho" } }]
    }
  } 
})
```
I guess certain fields of `BaseParameterObject` would collide (`description` for example), so maybe just allow a subset?

**Comment by tcaputi** [comment]
Any update on when this might happen? I'd love to be able to use this instead of patching the json object i get back from the call.

**Comment by emdede** [comment]
+1 implemented trpc-openapi in our project today and this is what is displayed as default example values for some of our RegExes
![image](https://user-images.githubusercontent.com/64293438/231829264-ca6d17f2-c982-4c45-ba71-20f6bb619fcb.png)

**Comment by jlalmes** [comment]
This is now supported!

```ts
const appRouter = t.router({
  queryExample: t.procedure
    .meta({
      openapi: {
        method: 'GET',
        path: '/query-example/{name}',
        example: {
          request: { name: 'James', greeting: 'Hello' },
          response: { output: 'Hello James' },
        },
      },
    })
    .input(z.object({ name: z.string(), greeting: z.string() }))
    .output(z.object({ output: z.string() }))
    .query(({ input }) => ({
      output: `${input.greeting} ${input.name}`,
    })),
```
