### ISSUE TITLE
The delete method does not accept arrays

### ISSUE THREAD

**Issue by Awolize** [jlalmes/trpc-openapi#262]
I have the following code but it seems to be mad about the ids number array. Is this an error on my part? Is the delete method a query instead of mutation or am I missing something else?

```
   removeSensor: customerProcedure
        .meta({
            openapi: {
                method: "DELETE",
                path: "/sensor/multi-delete",
                tags: ["Sensor"],
                protect: true,
            },
        })
        .input(
            z.object({
                ids: z.array(z.number()),
            })
        )
        .output(...)
        .mutation(async ({ input }) => { ... }
```
`TRPCError: [mutation.sensor.removeSensor] - Input parser key: "ids" must be ZodString, ZodNumber, ZodBoolean, ZodBigInt or ZodDate`

EDIT: I was reading up a bit more about the delete method and it seems that only some accepts a request body.

**Comment by jlalmes** [comment]
Yeah, the delete method cannot have a request body, so we must accept this via URL search params. 

There's a bit of work to do to decide how we want to support & implement `z.array()` in this case:

1. Accept `ZodString, ZodNumber, ZodBoolean, ZodBigInt or ZodDate` as comma-separated values?
2. Accept these as additional query params ie. `/users?ids=1&ids=2&ids=3`? (should we handle pluralization?)
3. Both of the above?

(cc. https://github.com/jlalmes/trpc-openapi/issues/240)
