### ISSUE TITLE
Cloudflare Workers adapter

### ISSUE THREAD

**Issue by hanssonduck** [jlalmes/trpc-openapi#266]
Hello, awesome project!
How difficult would it be to make this work with workers (and others like Deno)?
Maybe it's possible to refactor the code and strip out the Node dependencies from the core logic? 
Looking at the code this seems plausible since it only really the stuff from the trpc node adapter that's used.

**Comment by rkacenski** [comment]
Hey @jlalmes, cool project!.. what help might be needed for deploying to Cloudflare Workers?
