### ISSUE TITLE
Any plans for supporting a typesafe REST client?

### ISSUE THREAD

**Issue by aaronvg** [jlalmes/trpc-openapi#267]
I was thinking this package could provide a client that could call the REST endpoints in a typesafe manner.

It'd allow trpc servers to expose APIs more easily to external parties.

For example:
https://github.com/ecyrbe/zodios

**Comment by ssijak** [comment]
also interested in this, something similar to https://ts-rest.com/

**Comment by Nick-Lucas** [comment]
You probably want this:

https://github.com/jlalmes/trpc-openapi

If working in typescript it's a moot point, you just use the tRPC client for type-safety, other languages will benefit from OpenAPI definitions for code generation though
