### ISSUE TITLE
Add attribute level documention

### ISSUE THREAD

**Issue by krisgrm** [jlalmes/trpc-openapi#268]
API that I am working on is quite complex and it would be great if I could add some comments above each attribute in the `input` object and have that be also included with the openapi spec 

If you can show me how to do it, I can also look into tackling this

**Comment by mathisobadia** [comment]
If I understand you question correctly you can just use the zod describe method like this:

```js
    .input(z.object({ text: z.string().describe("The new todo's text") }))
```
and this will be included in the spec as a description field
