### ISSUE TITLE
Split openapi definition into components + requests for easier type generation to python

### ISSUE THREAD

**Issue by aaronvg** [jlalmes/trpc-openapi#274]
I'm trying to use https://github.com/koxudaxi/datamodel-code-generator to generate python types but the openapi.json file generated by this library doesn't output OpenAPI models that are used in each request (every request just has the inline schema defined) which is required by this other lib.

Would be awesome to split things out into proper models so we can have a TRPC <> openAPI <> python types/ client bridge :).

Thanks for making this library!

**Comment by jlalmes** [comment]
Hi @aaronvg, thanks for opening this issue! It is already being tracked here 👉 https://github.com/jlalmes/trpc-openapi/issues/157#issuecomment-1239368358
