### ISSUE TITLE
operationId is not a valid identifier

### ISSUE THREAD

**Issue by transitive-bullshit** [jlalmes/trpc-openapi#286]
According to the [spec](https://swagger.io/docs/specification/paths-and-operations/), `operationId` should be a valid identifier. The current version uses periods in-between operation parts, whereas it should slugify things together preferably using camelCase as that's what all the example OpenAPI specs seem to use.

**Comment by tianwg** [comment]
I'm facing the same issue, as a workaround I made a slight change in my fork and published it here https://www.npmjs.com/package/@tianwg/trpc-openapi
