### ISSUE TITLE
Handle nextjs 13 App directory 

### ISSUE THREAD

**Issue by Frumba** [jlalmes/trpc-openapi#289]
Hi,

I am currently trying to use trpc open api on nextjs new app directory structure. (nextjs 13)

The issue is that request and response of the new [route handlers](https://beta.nextjs.org/docs/routing/route-handlers) are incompatible with with the core http/node you have.

Here is the type of the request: https://beta.nextjs.org/docs/api-reference/request and the response: https://beta.nextjs.org/docs/api-reference/response

Have you planned to handle this case too ?

Thanks a lot !

**Comment by dschlabach** [comment]
@Frumba were you able to figure this out?

**Comment by flauschi** [comment]
Is there already progress on this issue?
Would be great to use trpc-openapi in the App directory.

**Comment by dschlabach** [comment]
Jack Herrington has a nice video about how to set up Next13 in the app directory, if anyone's looking for a solution:

https://www.youtube.com/watch?v=qCLV0Iaq9zU&t=2s

**Comment by Frumba** [comment]
> @Frumba were you able to figure this out?

I removed this package from my app
