### ISSUE TITLE
Add OpenID in security schemes

### ISSUE THREAD

**Issue by ben-ikt** [jlalmes/trpc-openapi#290]
Hi,

I cannot modify the security policy as it is hard-coded. I would like to add OpenID in security schemes

https://github.com/jlalmes/trpc-openapi/blob/b02225773e715ff6732b9395735259f967402d4d/src/generator/index.ts#L39

**Comment by jlalmes** [comment]
You can now set securitySchemes as an option on your generateOpenApiDocument function.

Try something like this! 👇

const openApiDocument = generateOpenApiDocument(appRouter, {
  title: 'tRPC OpenAPI',
  version: '1.0.0',
  baseUrl: 'http://localhost:3000/api',
  securitySchemes: {
    ApiKey: {
      type: 'apiKey',
      in: 'header',
      name: 'X-API-Key',
    },
  },
})
