### ISSUE TITLE
prisma-zod-generator

### ISSUE THREAD

**Issue by peterarusanoff** [jlalmes/trpc-openapi#291]
Hey there 
If we could use prisma, zod generator along with this package it would have a serous impact 
We are using next / prisma / trpc along with the aforementioned. 
The problem is you cant take in the generated zod schemas 
and we must have output types which the generator does not currently take

**Comment by tianwg** [comment]
you can try `zod-prisma-types` it can generate output models

**Comment by jlalmes** [comment]
Also recommend taking a look at [`zod-prisma`](https://github.com/CarterGrimmeisen/zod-prisma)
