### ISSUE TITLE
cookie authentication with session_id?

### ISSUE THREAD

**Issue by Blankeos** [jlalmes/trpc-openapi#295]
How can I have a prompt for adding a session_id inside my cookie so I can authenticate with my requests? I'm not using the Authorization bearer scheme.

**Comment by jlalmes** [comment]
You can now set `securitySchemes` as an option on your `generateOpenApiDocument` function.

Try this! 👇

```ts
const openApiDocument = generateOpenApiDocument(appRouter, {
  title: 'tRPC OpenAPI',
  version: '1.0.0',
  baseUrl: 'http://localhost:3000/api',
  securitySchemes: {
    CookieAuth: {
      type: 'http',
      scheme: 'cookie',
      in: 'cookie',
      name: 'session_id',
    },
  },
})
```

**Comment by Blankeos** [comment]
Sick!! Thank you!
