### ISSUE TITLE
Nested router automatical path generation

### ISSUE THREAD

**Issue by Autumnlight02** [jlalmes/trpc-openapi#301]
Would it be possible to use nested routes to automatically generate routes? (im a noob)
so for exampel if i have a route under user/create, could I add meta data to user with the path /user and then only add a path under create with meta = /create instead of doing it from the user directly as path = /user/create

**Comment by jlalmes** [comment]
Not possible at this time. See https://github.com/jlalmes/trpc-openapi/issues/260
