### ISSUE TITLE
Why is output definition required?

### ISSUE THREAD

**Issue by pedropmedina** [jlalmes/trpc-openapi#337]
I'm not sure if I'm missing something, but I've found that creating the output schema is very tedious if not impossible oftentimes when returning a complex type. 

According to the docs you must `Both input and output parsers are present AND use Zod validation.`  in order to get this working. 

It would be great if we weren't force to define the output. Perhaps there's a ways of inferring the procedure return type instead?

**Comment by kadetXx** [comment]
@pedropmedina you can pass in `z.custom()` to output and validation will be skipped without affecting your trpc procedure response. The only downside is - you won't get a response schema on swagger docs as it'll be empty.

**Comment by musjj** [comment]
`z.custom()` makes all my trpc routes return `unknown`. Is there a way to skip validation only in the openapi side?
