### ISSUE TITLE
RFC: Support `number`, `boolean`, `Date` in query params

### ISSUE THREAD

**Issue by jqhoogland** [jlalmes/trpc-openapi#44]
Right now it's not possible to have `z.number()`'s in your input schema for GET requests. 
That makes sense since query params *are* strings (so you get an error like `Input parser key: "limit" must be ZodString`).

But often (I'm thinking especially of pagination), you need numbers. Right now, you can recreate similar functionality with `z.string().transform((s) => parseInt(s)`, but it's not ideal since you lose, for example, Zod's built-in min/max validation.

At a minimum, this deserves a mention in the documentation. If we're feeling more ambitious, we can introduce autoconversions to `number`/`date` for common types.

I'm happy to open a PR, but first wanted to hear what you think, @jlalmes.

**Comment by jlalmes** [comment]
Hi @jqhoogland!

You can use `z.preprocess` (https://github.com/colinhacks/zod#preprocess) to transform an input type while keeping Zod's built-in validations (i.e. min/max).

I do like the proposal to support `number`, `Date` **AND** `boolean` out of the box - this will help with frictionless `trpc-openapi` adoption.

I suggest using the following preprocessors. Let me know if you're keen to open a PR 🙌

```ts
// number
z.preprocess((arg) => {
  if (typeof arg === 'string') {
    return parseInt(arg);
  }
  return arg;
}, z.number() /* 👈 you can use .min()/max() validations here */)

// Date
z.preprocess((arg) => {
  if (typeof arg === "string") {
    return new Date(arg);
  }
  return arg;
}, z.date())

// boolean
z.preprocess((arg) => {
  if (typeof arg === "string") {
    if (arg === 'true' || arg === '1') {
      return true;
    }
    if (arg === 'false' || arg === '0') {
      return false;
    }
  }
  return arg;
}, z.boolean())
```

**Comment by jqhoogland** [comment]
Wait I see you've already opened a branch and gone crazy. You are a hero with those edge cases!

**Comment by drenther** [comment]
The `z.preprocess` needs to be inside the resolve or in the input schema?

**Comment by jlalmes** [comment]
Example: 

```ts
.query('getUsers', {
  input: z.object({
    limit: z.preprocess((arg) => (typeof arg === 'string' ? parseInt(arg) : arg), z.number().min(1).max(50)),
  }),
  /* ... */
})
```

**Comment by jlalmes** [comment]
Note to self: https://twitter.com/ecyrbedev/status/1567953183120699392
