### ISSUE TITLE
Defining procedures with no `input`

### ISSUE THREAD

**Issue by dodas** [jlalmes/trpc-openapi#5]
Defining a query/mutation with no `input` results in
```
TRPCError: [query.<queryName>] - Input parser expects a Zod validator
```
It's possible to workaround this by defining an empty input:
```tsx
input: z.object({}),
```
However, that way an empty object is expected when calling the query via TRPC client.
It's a legit use-case to have queries/mutations with no `input`, right? Can we allow omitting `input` in such cases?

**Comment by dodas** [comment]
I currently have queries/mutations with no `input` and they work fine with TRPC Client, without having to pass an empty object explicitly.
My problem is that now with `trpc-openapi`, I will have to make a breaking change to our TRPC api by requesting an empty object to be passed in:
```json
[{
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [],
    "message": "Required"
}]
```
Couldn't we fallback no `input` to `z.object({})` internally in `trpc-openapi`?

**Comment by jlalmes** [comment]
I think this would be best solved by allowing this:

```ts
input: z.void(),
```

Now your tRPC API would continue working as intended and `trpc-openapi` will be aware that you're explicitly opting out of expecting any input for schema generation.

Thoughts?

**Comment by dodas** [comment]
> This is not possible.

Curious about this; care to explain why it wouldn't be possible, please?

Using `z.void()` sounds fine too, I just don't see much benefit being explicit about having no `input`.

**Comment by jlalmes** [comment]
> Curious about this; care to explain why it wouldn't be possible, please?

### Zod validator (expects `void`)

```ts
.query('zodVoidInput', {
  input: z.void(),
  output: z.object({}),
  resolve: () => ({})
})
```
```ts
const inputParser = z.void();
```

Here `inputParser instanceof ZodVoid` therefore we can ignore `input`.

### Custom func validator (expects `string`)

```ts
.query('omitInput', {
  input: (raw: unknown) => {
    if (typeof raw !== 'string') {
      throw new TRPCError({
        code: 'BAD_REQUEST',
        message: 'Non string value',
      });
    }
    return raw;
  },
  output: z.object({}),
  resolve: () => ({})
})
```
```ts
const inputParser = (raw: unknown) => {
  if (typeof raw !== 'string') {
    throw new TRPCError({
      code: 'BAD_REQUEST',
      message: 'Non string value',
    });
  }
  return raw;
}
```

Here `typeof inputParser === 'function'` therefore we cannot generate an OpenAPI schema and must throw an error.

### Omitted input

```ts
.query('omitInput', {
  output: z.object({}),
  resolve: () => ({})
})
```
```ts
const inputParser = (input: unknown) => {
  if (input != null) {
    throw new TRPCError({
      code: 'BAD_REQUEST',
      message: 'No input expected',
    });
  }
  return undefined;
}
```

As you can see `typeof inputParser === 'function'`, we cannot differentiate between `Custom func validator` (above) and an omitted `input`, therefore we must throw an error in this case too.

**Comment by dodas** [comment]
Ah I see, thanks.

Seems like this is a limitation of trpc and could be potentially solved if trpc used a constant fallback parser and exported it, instead of creating an anonymous fn, so we could compare references.

Anyway, I am totally fine with using `z.void()`/`z.undefined()`/`z.never()`.

**Comment by jlalmes** [comment]
We are actively working on `tRPC v10` at the moment so I'll put a word in & there may be a better solution after the next major!

**Comment by jlalmes** [comment]
Hi @dodas.

Please upgrade to the newest release `trpc-openapi@0.1.0-alpha.22` so that you can use `input: z.void()`. Let me know if you have any issues.

Head's up that this release includes a breaking change - please see https://github.com/jlalmes/trpc-openapi/pull/11.
