### ISSUE TITLE
[Example NextJS] The inferred type of 'default' cannot be named without a reference

### ISSUE THREAD

**Issue by mshd** [jlalmes/trpc-openapi#56]
./src/pages/api/[...trpc].ts:6:1
Type error: The inferred type of 'default' cannot be named without a reference to '.pnpm/next@12.2.0_beenoklgwfttvph5dgxj7na7aq/node_modules/next'. This is likely not portable. A type annotation is necessary.

  4 | 
  5 | // Handle incoming OpenAPI requests
 6 | export default createOpenApiNextHandler({
    | ^
  7 |   router: appRouter,
  8 |   createContext,
  9 | });

**Comment by mshd** [comment]
Fixed after changing "trpc-openapi": "0.2.1-alpha.0", to     "trpc-openapi": "0.1.2",

**Comment by jlalmes** [comment]
I'd accidentally tagged the `0.2.1-alpha.0` development release as `latest`. (As you mentioned above) please ensure you are using `trpc-openapi@^0.1.3` & let me know if you are having any further issues!

**Comment by mshd** [comment]
Yes, you should probably continue with 0.2.2 since everyone will get the 0.2.1-alpha now
