### ISSUE TITLE
`ZodEnum` and `ZodNativeEnum` as `input` param

### ISSUE THREAD

**Issue by dodas** [jlalmes/trpc-openapi#6]
Can we support `ZodEnum` and `ZodNativeEnum` types as `input` params?
Both of these accept `string` as their input, so they should be compatible, right?

It currently throws with
```
TRPCError: [<procedureName>] - Input parser key: "<propName>" must be a ZodString
```

**Comment by jlalmes** [comment]
Added support, please can you try out `trpc-openapi@0.1.0-alpha.21`, a confirm working as intended?

**Comment by dodas** [comment]
Works great!
This leads to a great ux where the available values are displayed in Swagger UI and you also have a `<select>` where you can select the value when trying the query:
<img width="276" alt="Screenshot 2022-06-07 at 23 33 58" src="https://user-images.githubusercontent.com/14360171/172486733-61327dfe-8179-4b6d-9767-d8d15d13c725.png">
<img width="251" alt="Screenshot 2022-06-07 at 23 34 03" src="https://user-images.githubusercontent.com/14360171/172486745-28dab102-831d-4a4d-b0c8-7e309c1cf584.png">
