### ISSUE TITLE
Feat: tRPC V10 Support

### ISSUE THREAD

**Issue by mshd** [jlalmes/trpc-openapi#73]
Hi James, 
Is the tRPC alpha version 10 already supported? If not, when would it be possible?
Also since this package is so closely tied and useful to tRPC, has it been considered to be merged into the tRPC monorepo?

**Comment by mshd** [comment]
as it was previously
```
export const createRouter = () => {
  return trpc.router<Context, OpenApiMeta>();
};
```

I've tried to use it now like this:
`export const t = initTRPC<{ ctx: Context; meta: OpenApiMeta }>()();
`

However I get an error when using

`t.procedure.meta({ openapi: { enabled: true, .... } }).`

**Comment by jlalmes** [comment]
Hi @mshd - v10 is not supported yet. It might take me a couple of weeks to get to this, but feel free to open a PR yourself if this is a hard requirement! 🙌

**Comment by albertilagan** [comment]
@jlalmes Any updates on this? :)

**Comment by jlalmes** [comment]
@albertilagan still waiting for the public tRPC `alpha` to be released!

**Comment by ibrahimyaacob92** [comment]
looking forward on this

**Comment by jlalmes** [comment]
Just shipped tRPC v10 support. To get started, please see 👉 https://github.com/jlalmes/trpc-openapi/pull/143
