### ISSUE TITLE
Path params should be omitted from request body params

### ISSUE THREAD

**Issue by dodas** [jlalmes/trpc-openapi#8]
Currently, using path params in a mutation results in a openAPI schema where the given param is expected in both `requestBody` and  `parameters`. Instead, I would expect the given param to be omitted from the request body schema, since it's passed via path.

For example, in the method below I would expect `blueprintId` to be passed via path and Request body only containing `credentialId`.
<img width="647" alt="Screenshot 2022-06-08 at 00 11 18" src="https://user-images.githubusercontent.com/14360171/172492874-2eb6fd3d-8597-43b2-bff7-d038ec36a8ad.png">

**Comment by jlalmes** [comment]
Resolve in `trpc-openapi@0.1.0-alpha.22`.
